// <auto-generated />
namespace Trial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removeanswerattributefromrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removeanswerattributefromrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201705100320400_Remove answer attribute from request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
