// <auto-generated />
namespace Trial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcompositekeytosubmit_workson_workedon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcompositekeytosubmit_workson_workedon));
        
        string IMigrationMetadata.Id
        {
            get { return "201705060221091_add composite key to submit_workson_workedon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
