// <auto-generated />
namespace Trial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtypeattributetoRequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtypeattributetoRequests));
        
        string IMigrationMetadata.Id
        {
            get { return "201705092251052_add type attribute to Requests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
